// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Merchant struct {
	ID           int32          `json:"id"`
	MerchantName string         `json:"merchant_name"`
	Description  sql.NullString `json:"description"`
	Website      sql.NullString `json:"website"`
	Address      sql.NullString `json:"address"`
}

type Topup struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	WalletID    sql.NullInt32  `json:"wallet_id"`
	Amount      string         `json:"amount"`
	TopupDate   time.Time      `json:"topup_date"`
	Description sql.NullString `json:"description"`
}

type Transaction struct {
	ID              int32          `json:"id"`
	UserID          sql.NullInt32  `json:"user_id"`
	WalletID        sql.NullInt32  `json:"wallet_id"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transaction_date"`
	Description     sql.NullString `json:"description"`
}

type TransactionMerchant struct {
	TransactionID sql.NullInt32 `json:"transaction_id"`
	MerchantID    sql.NullInt32 `json:"merchant_id"`
}

type Transfer struct {
	ID           int32          `json:"id"`
	FromWalletID sql.NullInt32  `json:"from_wallet_id"`
	ToWalletID   sql.NullInt32  `json:"to_wallet_id"`
	Amount       string         `json:"amount"`
	TransferDate time.Time      `json:"transfer_date"`
	Description  sql.NullString `json:"description"`
}

type User struct {
	ID               int32     `json:"id"`
	Username         string    `json:"username"`
	Password         string    `json:"password"`
	Email            string    `json:"email"`
	PhoneNumber      string    `json:"phone_number"`
	RegistrationDate time.Time `json:"registration_date"`
}

type Wallet struct {
	ID       int32         `json:"id"`
	UserID   sql.NullInt32 `json:"user_id"`
	Balance  string        `json:"balance"`
	Currency string        `json:"currency"`
}

type Withdrawal struct {
	WithdrawalID   int32          `json:"withdrawal_id"`
	UserID         sql.NullInt32  `json:"user_id"`
	WalletID       sql.NullInt32  `json:"wallet_id"`
	Amount         string         `json:"amount"`
	WithdrawalDate time.Time      `json:"withdrawal_date"`
	Description    sql.NullString `json:"description"`
}
