// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: topup.sql

package db

import (
	"context"
)

const createTopUps = `-- name: CreateTopUps :one
INSERT INTO topups (
    user_id,
    wallet_id,
    amount,
    description

) VALUES (
    $1, $2, $3, $4
) RETURNINg id, user_id, wallet_id, amount, topup_date, description
`

type CreateTopUpsParams struct {
	UserID      int32   `json:"user_id"`
	WalletID    int32   `json:"wallet_id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

func (q *Queries) CreateTopUps(ctx context.Context, arg CreateTopUpsParams) (Topup, error) {
	row := q.db.QueryRowContext(ctx, createTopUps,
		arg.UserID,
		arg.WalletID,
		arg.Amount,
		arg.Description,
	)
	var i Topup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Amount,
		&i.TopupDate,
		&i.Description,
	)
	return i, err
}
