// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: withdrawals.sql

package db

import (
	"context"
)

const createwithdrawals = `-- name: Createwithdrawals :one
INSERT INTO withdrawals (
    user_id,
    wallet_id,
    amount,
    description
) VALUES (
    $1, $2, $3, $4
) RETURNINg id, user_id, wallet_id, amount, withdrawal_date, description
`

type CreatewithdrawalsParams struct {
	UserID      int32   `json:"user_id"`
	WalletID    int32   `json:"wallet_id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

func (q *Queries) Createwithdrawals(ctx context.Context, arg CreatewithdrawalsParams) (Withdrawal, error) {
	row := q.db.QueryRowContext(ctx, createwithdrawals,
		arg.UserID,
		arg.WalletID,
		arg.Amount,
		arg.Description,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Amount,
		&i.WithdrawalDate,
		&i.Description,
	)
	return i, err
}
